rocketmq:
  name-server: localhost:9876
  producer:
    group: SpringBootExampleProducerGroup
    send-message-timeout: 300000


demo:
  rocketmq:
    topic: SpringBootExampleProducerGroup_tag
      user: user-topic
    orderTopic: SpringBootExampleProducerGroup_order_tag
    msgExtTopic: SpringBootExampleProducerGroup_message_ext_tag
    transTopic: SpringBootExampleProducerGroup_transaction_tag
    bytesRequestTopic: bytesRequestTopic:tagA
    stringRequestTopic: stringRequestTopic:tagA
    objectRequestTopic: objectRequestTopic:tagA
    genericRequestTopic: genericRequestTopic:tagA
    extNameServer: 127.0.0.1:9876

